apiVersion: v1
kind: ServiceAccount
metadata:
  namepace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}-awf-executor
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}-awf-executor-role
rules:
  - apiGroups: ["argoproj.io"]
    resources:
      - workflows
      - workflowtasksets
      - workflowtasksets/status
      - workflowtemplates
      - cronworkflows
      - workflowartifactgctasks
      - workflowtaskresults
      - workfloweventbindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
      - pods/log
      - services
      - configmaps
      - secrets
      - persistentvolumeclaims
      - events
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.namespace }}-executor-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.namespace }}-awf-executor
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.namespace }}-awf-executor-role
  apiGroup: rbac.authorization.k8s.io

