apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-wf-scenar-2-a-io-bound-4-tasks-8
  namespace: team-a
spec:
  schedules:
  - '*/5 * * * *'
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  workflowSpec:
    serviceAccountName: team-a-awf-executor
    podMetadata:
      labels:
        pod_type: ephemeral_worker
    entrypoint: cron-wf-scenar-1-a-io-bound-4-task-dag
    arguments:
      parameters:
        - name: workflow_number
          value: 8
        - name: scheduling_interval
          value: "300"

    templates:
      - name: cron-wf-scenar-1-a-io-bound-4-task-dag
        inputs:
          parameters:
            - name: workflow_number
            - name: scheduling_interval
        dag:
          tasks:
            - name: task1-delete-s3-and-tables
              templateRef:
                clusterScope: true
                name: argo-wf-io-bound-generic-template
                template: io-bound-task
              arguments:
                parameters:
                  - name: workflow_number
                    value: "{{inputs.parameters.workflow_number}}"
                  - name: scheduling_interval
                    value: "{{inputs.parameters.scheduling_interval}}"
                  - name: last_result
                    value: "{}"
                  - name: python_script_path
                    value: "/app/src/scripts/task1_delete_s3_and_tables.py"

            - name: task2-s3-ingestion-and-compute
              dependencies:
                - task1-delete-s3-and-tables
              templateRef:
                clusterScope: true
                name: argo-wf-io-bound-generic-template
                template: io-bound-task
              arguments:
                parameters:
                  - name: workflow_number
                    value: "{{inputs.parameters.workflow_number}}"
                  - name: scheduling_interval
                    value: "{{inputs.parameters.scheduling_interval}}"
                  - name: last_result
                    value: "{{tasks.task1-delete-s3-and-tables.outputs.parameters.result}}"
                  - name: python_script_path
                    value: "/app/src/scripts/task2_s3_ingestion_and_compute.py"

            - name: task3-wait-external-service
              dependencies:
                - task2-s3-ingestion-and-compute
              templateRef:
                clusterScope: true
                name: argo-wf-io-bound-generic-template
                template: io-bound-task
              arguments:
                parameters:
                  - name: workflow_number
                    value: "{{inputs.parameters.workflow_number}}"
                  - name: scheduling_interval
                    value: "{{inputs.parameters.scheduling_interval}}"
                  - name: last_result
                    value: "{{tasks.task2-s3-ingestion-and-compute.outputs.parameters.result}}"
                  - name: python_script_path
                    value: "/app/src/scripts/task3_wait_external_service.py"

            - name: monte-carlo-task-4
              dependencies:
                - task3-wait-external-service
              templateRef:
                clusterScope: true
                name: argo-wf-io-bound-generic-template
                template: io-bound-task
              arguments:
                parameters:
                  - name: workflow_number
                    value: "{{inputs.parameters.workflow_number}}"
                  - name: scheduling_interval
                    value: "{{inputs.parameters.scheduling_interval}}"
                  - name: last_result
                    value: "{{tasks.task3-wait-external-service.outputs.parameters.result}}"
                  - name: python_script_path
                    value: "/app/src/scripts/task4_copy_s3_to_postgres.py"